service: message-post
app: message-api
org: denizozger

provider:
  name: aws
  runtime: nodejs10.x

  stage: dev
  region: eu-central-1

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeStream
        - dynamodb:GetRecords
        - dynamodb:GetShardIterator
        - dynamodb:ListStreams
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
    - Effect: Allow
      Action:
        - ses:SendEmail
      Resource: "arn:aws:ses:eu-west-1:710995169233:identity/denizozger@gmail.com"
    - Effect: Allow
      Action:
        - sns:Publish
      Resource: "arn:aws:sns:eu-central-1:710995169233:message-post-dev-email-topic"
  environment:
    DYNAMODB_TABLE: messages-${opt:stage, self:provider.stage}

functions:
  postMessage:
    handler: postMessage.postMessage
    events:
      - http:
          path: messages
          method: post
          cors: true
  listMessages:
    handler: listMessages.listMessages
    events:
      - http:
          path: messages
          method: get
          cors: true
  handleNewMessage:
    handler: handleNewMessage.handleNewMessages
    events:
#      - stream: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}/stream/1970-01-01T00:00:00.000"
      - stream: "arn:aws:dynamodb:eu-central-1:710995169233:table/messages-dev/stream/2019-08-27T20:54:42.847"
  handleEmailSent:
    handler: handleEmailSent.handleEmailSent
    events:
      - sns: "arn:aws:sns:eu-central-1:710995169233:message-post-dev-email-topic"

resources:
  Resources:
    MessagesTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
          -
            AttributeName: emailAddress
            AttributeType: S
#          -
#            AttributeName: emailSent
#            AttributeType: B
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
          -
            AttributeName: emailAddress
            KeyType: RANGE
#          -
#            AttributeName: emailSent
#            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
    EmailTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: EmailTopic
        TopicName: ${self:service}-${self:provider.stage}-email-topic
